# Generated by Django 4.2.2 on 2023-06-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.CharField(blank=True, max_length=20, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='peso',
            field=models.CharField(blank=True, max_length=10, verbose_name='Peso'),
        ),
    ]
