# Generated by Django 4.2.2 on 2023-06-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0002_producto_nombre_alter_producto_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nombre'),
        ),
    ]
