# Generated by Django 4.2.2 on 2023-06-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0003_alter_producto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.FloatField(max_length=2, primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
