# Generated by Django 4.2.2 on 2023-06-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0007_alter_producto_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='peso',
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(blank=True, default=0, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(blank=True, default=0, verbose_name='Precio'),
        ),
    ]
